### ISSUE TITLE
client spec for List is missing

### ISSUE THREAD

**Issue by schulz3000** [deepstreamIO/deepstream.io-client-specs#15]
client spec for List is missing

**Comment by yasserf** [comment]
List is actually just a record, so does not differ in specs.

You can look at deepstream.io-e2e for scenarios that are backed by the record specs. I'll update comment once I'm at a computer!

**Comment by yasserf** [comment]
hey @schulz3000,

Apologies, it seems like this went past me. We don't have client specs for lists since its pretty much a record.

We now have full e2e tests ( https://github.com/deepstreamIO/deepstream.io-e2e ) that tests lists and such. They are substantially more thorough and do not require you to write a backend component since you would be running against a real deepstream cluster.
