### ISSUE TITLE
Scenarios are not self-contained

### ISSUE THREAD

**Issue by YavorPaunov** [deepstreamIO/deepstream.io-client-specs#7]
Running individual scenarios should yield the same result as when running a complete feature. Similar to tests, scenarios should be self-contained and should not depend on other scenarios being executed previously. Currently, that's not the case.

For example, when executing the complete logging-in feature, everything passes:
`nodejs ./node_modules/cucumber/bin/cucumber.js --require ./step-definitions-server/step-definition-server.js --require ./step-definitions-client/ ./features/logging-in.feature`

However, when only one scenario is executed, it fails:
`nodejs ./node_modules/cucumber/bin/cucumber.js --require ./step-definitions-server/step-definition-server.js --require ./step-definitions-client/ ./features/logging-in.feature --name "too many"`

For steps that should be executed before every scenario in a feature, perhaps adding a [Background](https://github.com/cucumber/cucumber/wiki/Background) would be a good idea. A specific example would be adding this to logging-in.feature:

```
Background:
    Given the test server is ready
        And the client is initialised
```

This means that the server and client need to be torn down after each scenario.

There are some cases that cannot be solved by adding a background, like the TOO_MANY_AUTH_ATTEMPTS one, where the solutions is to simply add more steps that describe the scenario completely.

**Comment by yasserf** [comment]
hey @YavorPaunov ,

You are correct that tests are usually written with all state contained within a single scenario. The reason why we didn't do this is because the scenarios are built on their predecessors, meaning we wouldn't be able to push all of the scenarios into a background task and having the individual steps repeated in each scenario would be alot of duplication/noise. 

I understand this isn't the intended way the tool works specifically, but the idea is to run individual granular features that are independent instead of each individual scenario.

**Comment by yasserf** [comment]
I'll be closing this issue since we will not be updating the current test suite, but thank you for raising the issue regarding running individual scenarios, I'll keep it in mind going forward.
